[package]
name = "nen-emulator"
version = "0.1.0"
edition = "2021"


[dependencies]
bitflags = "2.6.0"
log = "0.4.22"
colog = "1.3.0"
sdl2 = "0.37.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
prettydiff = "0.7.0"
circular-buffer = "0.1.9"
rand = "0.8.5"
